### ISSUE TITLE
t(...).files.mkdir is not a function

### ISSUE THREAD

**Issue by coryl** [hacdias/ipfs-todo#1]
Installed and ran the app, running the IPFS chrome helper extension.

Get the message when trying to input anything:
t(...).files.mkdir is not a function

**Comment by hacdias** [comment]
@coryl you're using IPFS Companion with Embedded IPFS or with an external daemon?

**Comment by coryl** [comment]
Embedded.

**Comment by hacdias** [comment]
@coryl Yeah, the problem is that **js-ipfs** doesn't yet support MFS (Mutable File System). I just added a note on README about that.

Thanks for noticing that.
